### ISSUE TITLE
Hangs on Initialization

### ISSUE THREAD

**Issue by davidvanvo** [ExPHAT/homebridge-hunterdouglas#1]
Unable to get this to work. 

With port 522 I get a ECONNREFUSED error. Tried port 80 and I no longer see the error, but everything just hangs and will not proceed to the "Scan this code with your HomeKit App..." message.

**Comment by GvnCampbell** [comment]
Same here.  Just got my hub setup this weekend and was trying to get this working.  I get the same issues as reported.

**Comment by exPHAT** [comment]
@davidvanvo @GvnCampbell Do you have PowerView blinds or the previous generation? (Platinum shades I think they're called?)

**Comment by davidvanvo** [comment]
PowerView, or at least that's what's the name of the hub.

**Comment by GvnCampbell** [comment]
Same here.  I'm able to control them using the powerview app on my iPhone.

**Comment by exPHAT** [comment]
@davidvanvo @GvnCampbell This plugin was only designed to handle the generation before they released PowerView (since there was no actual API documentation). Pretty sure they have proper documentation for the PowerView API.

In the future, I'll see if I can add PowerView support

**Comment by GvnCampbell** [comment]
Ahhh.. makes sense.  Thanks for the reply.  

I saw this link talking about the API of the powerview blinds.  Not sure if it would help but sending it along anyways.

http://forum.universal-devices.com/topic/16538-hunter-douglas-powerview-control-with-isy/

**Comment by exPHAT** [comment]
@GvnCampbell I've linked the api docs directly from hunterdouglas in https://github.com/ExPHAT/node-hunterdouglas/issues/2, from what I can tell, its actually pretty similar, will require some changes to how I handle parsing. But hopefully should be easy to add.

**Comment by exPHAT** [comment]
Going to close this issue, if you have anything to add, head over to https://github.com/ExPHAT/node-hunterdouglas/issues/2
