### ISSUE TITLE
Two Attributes? 

### ISSUE THREAD

**Issue by mkrug1** [ExPHAT/homebridge-hunterdouglas#4]
Some drapes (such as the LUMINETTE) have two controllable attributes. (the percent open, and the percent of the vanes rotation.) 
The plug-in only controls the level of open, and not the rotation.  
Is it possible to add a second slider?

**Comment by exPHAT** [comment]
I don't believe HomeKit has support for dual sliders. Maybe if you use a 3rd party home app?

Functionality wise, I don't think it'd be too hard to implement

**Comment by mkrug1** [comment]
I wonder if it could be implemented similar to a color changing light bulb, where you can choose color and intensity independently… or a thermostat where the temperature and the mode (heating/cooling) are separate controls.

Thanks for this.  It is fantastic.  The HD app was awful, unreliable, and has been deprecated.  This fixes a lot of problems.

—MK

**Comment by exPHAT** [comment]
Closing this, as HomeKit doesn't have support for dual sliders. Hopefully one day!

**Comment by mkrug1** [comment]
Thanks for the consideration.
Any ideas about how to recall a position in the HD bridge?  Or having the two attributes as two separate devices in HomeKit?

--MK
(also looking forward to an Arduino HomeKit library!)
