### ISSUE TITLE
description say HD Platinum but JS files say powerview

### ISSUE THREAD

**Issue by cxvccxvc** [ExPHAT/homebridge-hunterdouglas#5]
Just wondering if this was written for hunter douglas powerview or platinum. The description of your project indicates platinum but in some of the JS files it says to use the powerview app (maybe you project works for both......just not sure)

Thanks
-chuck

**Comment by exPHAT** [comment]
This project only works with Platinum blinds.

I had originally assumed PowerView used the exact same internal setup, but I was wrong. I'll make sure to update the repo as not to cause confusion 😄

**Comment by cxvccxvc** [comment]
Awesome. Thanks. I was looking for platinum so this is good news

Thanks
Chuck


On Dec 21, 2018, at 15:48, Aaron Taylor <notifications@github.com<mailto:notifications@github.com>> wrote:


This project only works with Platinum blinds.

I had originally assumed PowerView used the exact same internal setup, but I was wrong. I'll make sure to update the repo as not to cause confusion 😄
